### 20221222074900 ###

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
    commit-message:
      prefix: "gha:"

  # Maintain dependencies for Go
  - package-ecosystem: "gomod"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
    commit-message:
      prefix: "golang:"
      
  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
    commit-message:
      prefix: "docker:"
